"""CLI: self-play + train loop for the AlphaZero-style Connect Four
network -- Stage 1 of the plan: a small, deliberate run whose only job is
to answer "does this learn anything at all" via two cheap, concrete
signals (win rate vs. a random opponent, and whether the network starts
finding k_plies=1 immediate-win puzzles from the existing generator it
was never shown during training), not to reach real playing strength.
Checkpointed every iteration (weights + optimizer + replay buffer +
iteration count) since this is expected to span multiple sessions.
"""

from __future__ import annotations

import argparse
import random
import time
from pathlib import Path

import numpy as np
import torch

from ..datasets import connect_four
from ..datasets.connect_four_engine import X
from .network import ConnectFourNet
from .network import evaluate as net_evaluate
from .puct import PUCTConfig, is_solved, run_search
from .selfplay import play_game, play_vs_random
from .train import ReplayBuffer, train_step


def _evaluate_puzzle_solving(net, device, n_puzzles: int, budget: int, k_plies: int, seed: int) -> float:
    puzzles = connect_four.generate_puzzles(n_low=n_puzzles, n_high=0, seed=seed, width=5, height=4, k_plies=k_plies, max_pre_moves=8)
    rng = np.random.default_rng(seed)

    def evaluate_fn(board, to_move):
        return net_evaluate(net, board, to_move, device)

    solved = 0
    for inst in puzzles:
        config = PUCTConfig(merge_enabled=True, c_puct=1.5, dirichlet_alpha=None)
        graph = run_search(inst.pre_moves, inst.to_move, 5, config, budget, evaluate_fn, rng)
        if is_solved(graph, hero=inst.to_move):
            solved += 1
    return solved / len(puzzles)


def _evaluate_win_rate(net, device, n_games: int, budget: int, seed: int) -> float:
    rng = np.random.default_rng(seed)

    def evaluate_fn(board, to_move):
        return net_evaluate(net, board, to_move, device)

    total = 0.0
    for i in range(n_games):
        network_plays = X if i % 2 == 0 else "O"
        total += play_vs_random(evaluate_fn, budget, c_puct=1.5, rng=rng, network_plays=network_plays)
    return total / n_games


def main():
    ap = argparse.ArgumentParser(description="AlphaZero-style Connect Four self-play + training (Stage 1)")
    ap.add_argument("--iterations", type=int, default=10)
    ap.add_argument("--games-per-iteration", type=int, default=20)
    ap.add_argument("--selfplay-budget", type=int, default=50, help="PUCT simulations per move during self-play")
    ap.add_argument("--c-puct", type=float, default=1.5)
    ap.add_argument("--temperature-moves", type=int, default=6)
    ap.add_argument("--dirichlet-alpha", type=float, default=0.5)
    ap.add_argument("--dirichlet-epsilon", type=float, default=0.25)
    ap.add_argument("--replay-buffer-size", type=int, default=10_000)
    ap.add_argument("--batch-size", type=int, default=64)
    ap.add_argument("--train-steps-per-iteration", type=int, default=50)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--channels", type=int, default=48)
    ap.add_argument("--num-blocks", type=int, default=3)
    ap.add_argument("--eval-games", type=int, default=20, help="games vs. random per evaluation")
    ap.add_argument("--eval-puzzles", type=int, default=10, help="forced-win puzzles per evaluation")
    ap.add_argument("--eval-k-plies", type=int, default=3, help="puzzle difficulty for the puzzle-solving check")
    ap.add_argument("--eval-budget", type=int, default=30, help="PUCT simulations per move during evaluation")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--resume-from", default=None)
    ap.add_argument("--output-dir", default="results/alphazero_connect_four")
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    net = ConnectFourNet(channels=args.channels, num_blocks=args.num_blocks).to(args.device)
    optimizer = torch.optim.Adam(net.parameters(), lr=args.lr)
    buffer = ReplayBuffer(args.replay_buffer_size)
    start_iteration = 0

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.resume_from:
        # weights_only=False: this checkpoint is self-generated by this same script (its
        # replay buffer holds SelfPlayExample objects, which PyTorch 2.6+'s default
        # weights_only=True refuses to unpickle) -- never load a checkpoint from an
        # untrusted source this way.
        ckpt = torch.load(args.resume_from, map_location=args.device, weights_only=False)
        net.load_state_dict(ckpt["net"])
        optimizer.load_state_dict(ckpt["optimizer"])
        buffer.buffer.extend(ckpt["buffer"])
        start_iteration = ckpt["iteration"]
        print(f"resumed from {args.resume_from} at iteration {start_iteration}")

    sampler = random.Random(args.seed)
    log_path = out_dir / "train_log.jsonl"

    for iteration in range(start_iteration, args.iterations):
        t0 = time.time()
        rng = np.random.default_rng(args.seed * 1000 + iteration)

        def evaluate_fn(board, to_move):
            return net_evaluate(net, board, to_move, args.device)

        for _ in range(args.games_per_iteration):
            examples = play_game(
                evaluate_fn, args.selfplay_budget, args.c_puct, args.temperature_moves,
                args.dirichlet_alpha, args.dirichlet_epsilon, rng,
            )
            buffer.add_game(examples)

        losses = []
        if len(buffer) >= args.batch_size:
            for _ in range(args.train_steps_per_iteration):
                batch = buffer.sample(args.batch_size, sampler)
                losses.append(train_step(net, optimizer, batch, args.device))

        win_rate = _evaluate_win_rate(net, args.device, args.eval_games, args.eval_budget, args.seed * 1000 + iteration)
        puzzle_rate = _evaluate_puzzle_solving(net, args.device, args.eval_puzzles, args.eval_budget, args.eval_k_plies, args.seed * 1000 + iteration)

        mean_loss = sum(l["loss"] for l in losses) / len(losses) if losses else float("nan")
        elapsed = time.time() - t0
        print(f"iter {iteration}: buffer={len(buffer)} mean_loss={mean_loss:.4f} "
              f"win_vs_random={win_rate:.3f} puzzle_solve={puzzle_rate:.3f} ({elapsed:.1f}s)")

        with open(log_path, "a") as f:
            f.write(f'{{"iteration": {iteration}, "buffer_size": {len(buffer)}, "mean_loss": {mean_loss}, '
                     f'"win_vs_random": {win_rate}, "puzzle_solve_rate": {puzzle_rate}, "elapsed_sec": {elapsed}}}\n')

        torch.save({
            "net": net.state_dict(), "optimizer": optimizer.state_dict(),
            "buffer": list(buffer.buffer), "iteration": iteration + 1,
        }, out_dir / "checkpoint.pt")

    print(f"done -> {out_dir}")


if __name__ == "__main__":
    main()
